"""empty message

Revision ID: e4f5466e0a76
Revises: f30acbc0b7f8
Create Date: 2021-09-13 11:02:06.480576

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e4f5466e0a76'
down_revision = 'f30acbc0b7f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('artists', 'gen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('gen', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('artists', 'genres')
    # ### end Alembic commands ###
