"""empty message

Revision ID: f30acbc0b7f8
Revises: 721a59be678c
Create Date: 2021-09-13 11:01:40.193040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f30acbc0b7f8'
down_revision = '721a59be678c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('gen', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('artists', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('artists', 'gen')
    # ### end Alembic commands ###
